### ISSUE TITLE
Add correct datetime parsing to admin

### ISSUE THREAD

**Issue by jgujgu** [jgujgu/solidus_auction#11]

**Comment by jgujgu** [comment]
https://robots.thoughtbot.com/its-about-time-zones

**Comment by jgujgu** [comment]
https://www.varvet.com/blog/working-with-time-zones-in-ruby-on-rails/
http://timepicker.co/
https://stackoverflow.com/questions/4269270/rails-3-setting-the-timezone-to-the-current-users-timezone

**Comment by jgujgu** [comment]
Separate date, time, and zone, for user, but still use datetime in database.

**Comment by jgujgu** [comment]
http://danilenko.org/2012/7/6/rails_timezones/

**Comment by smsouthard** [comment]
lol that guys hair
