### ISSUE TITLE
Add auction, bid models

### ISSUE THREAD

**Issue by jgujgu** [jgujgu/solidus_auction#2]
https://stackoverflow.com/questions/3278986/ago-date-time-functions-in-ruby-rails
https://stackoverflow.com/questions/4654457/how-to-add-10-days-to-current-time-in-rails/4654484

**Comment by jgujgu** [comment]
Possible data model. "Bid Order" is another name for "Auction".
http://www.vertabelo.com/blog/technical-articles/an-online-auction-data-model

**Comment by jgujgu** [comment]
http://www.databaseanswers.org/data_models/auction/index.htm

**Comment by jgujgu** [comment]
https://nnodes.com/blog/2016/custom-model-with-spree

**Comment by ahwong5** [comment]
Thanks for your contribution and sharing, looking forward for this extension and learning from the info you pasted in this thread. TQ!

ahwong5 (RoR newbie)

**Comment by jgujgu** [comment]
You're welcome! I hope I can make this a high quality gem.
